language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install flake8 mock pytest pytest-cov python-coveralls sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs docs/_build
    - python -m sphinx -b html -W docs docs/_build
    - py.test -s -v --cov=binarytree
after_success:
    - coveralls
